/*
 * Author: WaldoTheWarfighter
 * Supplies a culturally neutral, opt-in civilian dialogue pack for modern operations.
 * Locality/authority: pure server-loaded data. Repeat/JIP behaviour: no side effects.
 * Arguments: None. Return Value: HASHMAP of archetype ID to ARRAY<STRING>.
 * Current caller: Waldo_fnc_DialogueLoadPresetPack. Example: ["MODERN_CIVILIANS"] call Waldo_fnc_DialogueLoadPresetPack;
 */
createHashMapFromArray [
    ["MODERN_CIVILIAN", ["Hello.", "Can I help you?", "Is the road open?", "We are just trying to get through the day.", "I have not heard anything reliable.", "Please leave the gate as you found it.", "The market was quieter this morning.", "Everyone is waiting for things to calm down.", "You should ask someone at the municipal building.", "Stay safe out there."]],
    ["MODERN_CIVILIAN_FRIENDLY", ["Good to see you.", "Do you need directions?", "There is clean water at the community centre.", "The clinic is still open.", "I can show you the safer road.", "People will talk if you listen patiently.", "Thank you for checking on us.", "The neighbourhood has been quiet today.", "Let me know if somebody needs help.", "Take care of yourselves."]],
    ["MODERN_CIVILIAN_WARY", ["What do you want?", "I do not want any trouble.", "Please keep your distance.", "I have nothing to tell you.", "People are nervous when armed strangers arrive.", "Ask your questions and move on.", "My family is inside.", "We are not taking sides.", "I did not see who came through here.", "Please leave us alone."]],
    ["MODERN_CIVILIAN_DISPLACED", ["We left with only what we could carry.", "Do you know where the reception point is?", "We have been waiting for transport since morning.", "Some families became separated on the road.", "The children need water and somewhere warm.", "We were told this route was safe.", "I do not know whether our home is still standing.", "The aid workers took our names earlier.", "Please tell us if the situation changes.", "We just need somewhere safe tonight."]],
    ["MODERN_SHOPKEEPER", ["We are open, but supplies are limited.", "Please do not block the doorway.", "Cash only; the network is down again.", "Fresh deliveries have not arrived yet.", "I can set some essentials aside.", "The shelves empty quickly these days.", "Ask before taking photographs inside.", "The back room is staff only.", "People have been buying batteries and bottled water.", "Come back tomorrow and I may know more."]],
    ["MODERN_RURAL_RESIDENT", ["The track floods after heavy rain.", "Livestock have been restless all morning.", "There is another crossing beyond the fields.", "Please close the fence behind you.", "The mobile signal barely reaches here.", "We heard vehicles during the night.", "The well is shared by three families.", "The old bridge will not carry anything heavy.", "Most people went into town for supplies.", "Mind the irrigation ditch by the road."]],
    ["MODERN_AID_WORKER", ["Please keep the access lane clear.", "The clinic is handling urgent cases first.", "We are registering families one at a time.", "Water distribution begins again this afternoon.", "Do not move the marked medical supplies.", "We need a clear route for the ambulance.", "The missing-person list is at the desk.", "Security conditions may change our schedule.", "Speak to the coordinator before entering the shelter.", "Thank you for keeping the crowd calm."]],
    ["MODERN_LOCAL_OFFICIAL", ["The municipal office is operating with reduced staff.", "Emergency services have priority on this road.", "We are confirming reports before making an announcement.", "The public shelter opens at dusk.", "Please coordinate movements through the operations desk.", "Utility crews are assessing the damage.", "The curfew notice is posted at the main square.", "We need written details for every request.", "Community representatives meet here each morning.", "I will pass that information to the duty officer."]]
]
