"""Check executable Cortex coverage wiring without claiming behavioural acceptance."""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
REQUIRED_CASE_FIELDS = {
    "id", "title", "setup", "expected", "settings", "status",
    "live_evidence", "automation", "executable_sources", "production_sources",
}
PUBLIC_RUNTIME_CONTROLS = {
    "Waldo_AIPass_Exclude",
    "Waldo_AIPass_Profile",
    "Waldo_HelicopterDeceleration_Exclude",
}


def render_markdown(data):
    """Render an honest per-feature depth matrix from the checked coverage registry."""
    lines = [
        "# Cortex acceptance depth",
        "",
        "Generated by `check_cortex_coverage.py --write-report`. Runnable fixtures and saved evidence are",
        "inventory signals only. A feature is accepted only when its registry status is `accepted`.",
        "",
        f"Feature cases: **{len(data['cases'])}**. Required variant categories: **{len(data['required_variants'])}**.",
        "",
        "| Feature | Settings | Per-asset controls | Production sources | Runnable suites | Evidence records | Status |",
        "| --- | ---: | ---: | ---: | --- | ---: | --- |",
    ]
    for case in data["cases"]:
        sources = ", ".join(f"`{source}`" for source in case["executable_sources"])
        lines.append(
            f"| {case['id']} - {case['title']} | {len(case['settings'])} | {len(case.get('controls', []))} | "
            f"{len(case['production_sources'])} | {sources} | "
            f"{len(case['live_evidence'])} | {case['status']} |"
        )
    lines.extend(["", "## Required variants", ""])
    lines.extend(f"- {variant}" for variant in data["required_variants"])
    lines.extend(["", "## Per-feature scope and remaining work", ""])
    for case in data["cases"]:
        lines.extend([
            f"### {case['id']} - {case['title']}",
            "",
            f"**Expected:** {case['expected']}",
            "",
            f"**Automation and open work:** {case['automation']}",
            "",
        ])
    return "\n".join(lines).rstrip() + "\n"

def audit(root=ROOT):
    tools = root / "releaseVerificationAndDeployment"
    qa = tools / "cortexQA"
    data = json.loads((qa / "coverage.json").read_text(encoding="utf-8"))
    launcher = (tools / "launch_pr_review_audit.ps1").read_text(encoding="utf-8")
    server = (qa / "runServer.sqf").read_text(encoding="utf-8")
    settings = set(re.findall(r'^\s*\["(Waldo_[^"]+)"\s*,',
        (root / "MissionConfig/aiConfig.sqf").read_text(encoding="utf-8"), re.M))
    assigned = [key for case in data["cases"] for key in case["settings"]]
    errors = []
    if settings != set(assigned):
        errors.append(f"Setting coverage mismatch: missing={sorted(settings-set(assigned))}; obsolete={sorted(set(assigned)-settings)}")
    if len(assigned) != len(set(assigned)):
        errors.append("Settings assigned to multiple feature cases")
    controls = [key for case in data["cases"] for key in case.get("controls", [])]
    if set(controls) != PUBLIC_RUNTIME_CONTROLS:
        errors.append(f"Runtime control coverage mismatch: missing={sorted(PUBLIC_RUNTIME_CONTROLS-set(controls))}; obsolete={sorted(set(controls)-PUBLIC_RUNTIME_CONTROLS)}")
    if len(controls) != len(set(controls)):
        errors.append("Runtime controls assigned to multiple feature cases")
    production_root = root / "MissionScripts/AiScripting"
    production = {
        path.relative_to(root).as_posix()
        for path in production_root.rglob("*.sqf")
        if path.is_file()
    }
    assigned_sources = [
        source
        for case in data["cases"]
        for source in case.get("production_sources", [])
    ]
    if production != set(assigned_sources):
        errors.append(
            "Production source coverage mismatch: "
            f"missing={sorted(production-set(assigned_sources))}; "
            f"obsolete={sorted(set(assigned_sources)-production)}"
        )
    if len(assigned_sources) != len(set(assigned_sources)):
        errors.append("Production AI sources assigned to multiple feature cases")
    ids = [case["id"] for case in data["cases"]]
    if len(ids) != len(set(ids)):
        errors.append("Duplicate feature case IDs")
    for case in data["cases"]:
        missing_fields = sorted(REQUIRED_CASE_FIELDS-set(case))
        if missing_fields:
            errors.append(f"{case.get('id','<unknown>')}: missing fields {missing_fields}")
            continue
        if case["status"] not in {"implemented_partial", "accepted"}:
            errors.append(f"{case['id']}: invalid acceptance status {case['status']}")
        if not case["setup"] or not case["expected"] or not case["automation"]:
            errors.append(f"{case['id']}: empty setup, expected result or automation scope")
        for production_source in case["production_sources"]:
            if not (root / production_source).is_file():
                errors.append(f"{case['id']}: missing production source {production_source}")
        sources = case.get("executable_sources", [])
        if not sources:
            errors.append(f"{case['id']}: no executable source")
        for source in sources:
            if Path(source).name != source or not (qa / source).is_file():
                errors.append(f"{case['id']}: missing or invalid source {source}")
                continue
            # A source file by itself is not runnable: check staging and dispatch.
            pattern = r'cortexQA/' + re.escape(source) + r'"\) -Destination \(Join-Path \$missionRoot "([^"]+)"'
            match = re.search(pattern, launcher)
            if not match:
                errors.append(f"{case['id']}: {source} is not staged by the launcher")
            elif source not in ["runServer.sqf", "runClient.sqf"] and match[1] not in server:
                errors.append(f"{case['id']}: staged {source} has no server dispatch")
    pending = [case["id"] for case in data["cases"] if case.get("status") != "accepted"]
    return data, errors, pending

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--require-accepted", action="store_true")
    parser.add_argument("--write-report", type=Path, metavar="PATH")
    args = parser.parse_args()
    data, errors, pending = audit()
    source_count = sum(len(case["production_sources"]) for case in data["cases"])
    print(
        f"Executable coverage: {len(data['cases'])} feature cases; "
        f"{len(data['required_variants'])} required variant categories; "
        f"{source_count} production AI sources"
    )
    for error in errors:
        print("ERROR: " + error)
    print("Incomplete behavioural acceptance: " + ", ".join(pending))
    print("Wiring checks do not prove physical behaviour or complete variant coverage.")
    if args.write_report:
        output = args.write_report if args.write_report.is_absolute() else ROOT / args.write_report
        output.write_text(render_markdown(data), encoding="utf-8")
        print(f"Wrote per-feature acceptance depth report: {output}")
    return 1 if errors else (2 if args.require_accepted and pending else 0)

if __name__ == "__main__":
    raise SystemExit(main())
