/*
 * Author: WaldoTheWarfighter
 * Waldos Mini Games - Five-Card Draw
 * Server-authoritative ante, two no-limit betting rounds, one draw and side pots.
 * Hands remain server-only and are delivered solely to their owning clients.
 * Locality/authority: Server rules and hands are authoritative; controls are interface-local.
 * Repeat/JIP: Compiled once per role; named snapshots restore only audience-permitted state.
 * Arguments: None; include fragment.
 * Return Value: Nothing; defines runtime functions.
 * Current callers: Waldo_fnc_MiniGamesEnsureRuntime.
 * Example: [this] call Waldo_fnc_MiniGamesRegisterTable;
 */

Waldo_MG_fnc_drawPokerPublishServer = {
    params [["_table",objNull]]; if (!isServer || {isNull _table}) exitWith {};
    _table setVariable ["Waldo_MG_DrawPokerRevision",(_table getVariable ["Waldo_MG_DrawPokerRevision",0])+1,true];
    _table setVariable ["Waldo_MG_TableRevision",(_table getVariable ["Waldo_MG_TableRevision",0])+1,true];
};

Waldo_MG_fnc_drawPokerSendHandsServer = {
    params [["_table",objNull]]; if (!isServer || {isNull _table}) exitWith {};
    private _players=_table getVariable ["Waldo_MG_DrawPokerPlayers",[]]; private _hands=_table getVariable ["Waldo_MG_DrawPokerHandsServer",[]];
    private _gameId=_table getVariable ["Waldo_MG_DrawPokerGameId",""]; private _handNo=_table getVariable ["Waldo_MG_DrawPokerHandNumber",0];
    {if (!isNull _x) then {_x setVariable ["Waldo_MG_DrawPokerPrivateHand",[_gameId,_handNo,+(_hands param [_forEachIndex,[]])],owner _x];};} forEach _players;
};

Waldo_MG_fnc_drawPokerNextRole = {
    params [["_start",-1],["_statuses",[]],["_includeAllIn",false]]; private _result=-1; private _count=count _statuses;
    for "_offset" from 1 to _count do {private _candidate=(_start+_offset) mod _count; private _state=_statuses param [_candidate,"LEFT"]; if (_result<0 && {_state=="ACTIVE" || {_includeAllIn && {_state=="ALLIN"}}}) then {_result=_candidate;};}; _result
};

Waldo_MG_fnc_drawPokerSetStatusServer = {
    params [["_table",objNull],["_text",""]]; if (!isServer || {isNull _table}) exitWith {}; _table setVariable ["Waldo_MG_DrawPokerStatus",_text,true]; [_table] call Waldo_MG_fnc_drawPokerPublishServer;
};

Waldo_MG_fnc_drawPokerResolveHandServer = {
    params [["_table",objNull],["_reason",""]]; if (!isServer || {isNull _table}) exitWith {};
    private _statuses=+(_table getVariable ["Waldo_MG_DrawPokerStatuses",[]]); private _contrib=_table getVariable ["Waldo_MG_DrawPokerTotalContrib",[]]; private _chips=+(_table getVariable ["Waldo_MG_DrawPokerChips",[]]);
    private _hands=_table getVariable ["Waldo_MG_DrawPokerHandsServer",[]]; private _names=_table getVariable ["Waldo_MG_DrawPokerPlayerNames",[]]; private _contenders=[];
    {if !(_x in ["FOLDED","LEFT","SITOUT"]) then {_contenders pushBack _forEachIndex;};} forEach _statuses;
    private _summary=[];
    if ((count _contenders)==1) then {
        private _winner=_contenders select 0; private _pot=0; {_pot=_pot+_x;} forEach _contrib; _chips set [_winner,(_chips param [_winner,0])+_pot];
        _summary pushBack format ["%1 wins %2 chips uncontested.",_names param [_winner,"Player"],_pot];
    } else {
        private _scores=[]; {_scores pushBack ([_x] call Waldo_MG_fnc_pokerEvaluateFive);} forEach _hands;
        private _pots=[_contrib,_statuses] call Waldo_MG_fnc_pokerBuildSidePots;
        {
            _x params ["_amount","_eligible"];
            private _winners=[]; private _best=[];
            {private _score=_scores param [_x,[-1]]; private _cmp=if ((count _best)==0) then {1} else {[_score,_best] call Waldo_MG_fnc_pokerCompareScores}; if (_cmp>0) then {_best=_score;_winners=[_x];} else {if (_cmp==0) then {_winners pushBack _x;};};} forEach _eligible;
            if ((count _winners)>0) then {private _share=floor (_amount/(count _winners)); private _remainder=_amount-(_share*(count _winners)); {_chips set [_x,(_chips param [_x,0])+_share+(if (_forEachIndex<_remainder) then {1}else{0})];} forEach _winners; _summary pushBack format ["%1: %2 chips to %3 (%4).",if (_forEachIndex==0) then {"Main pot"}else{format ["Side pot %1",_forEachIndex]},_amount,(_winners apply {_names param [_x,"Player"]}) joinString ", ",[_best] call Waldo_MG_fnc_pokerHandCategoryName];};
        } forEach _pots;
        private _revealed=[]; {if (_forEachIndex in _contenders) then {_revealed pushBack [_forEachIndex,+_x];};} forEach _hands; _table setVariable ["Waldo_MG_DrawPokerRevealed",_revealed,true];
    };
    private _funded=[]; {if (_x>0 && {(_statuses param [_forEachIndex,""])!="LEFT"}) then {_funded pushBack _forEachIndex;};} forEach _chips;
    private _matchOver=(count _funded)<=1;
    _table setVariable ["Waldo_MG_DrawPokerChips",_chips,true]; _table setVariable ["Waldo_MG_DrawPokerPhase",if (_matchOver) then {"FINISHED"}else{"HAND_OVER"},true]; _table setVariable ["Waldo_MG_DrawPokerTurn",-1,true]; _table setVariable ["Waldo_MG_DrawPokerReady",(_chips apply {false}),true]; _table setVariable ["Waldo_MG_DrawPokerFinished",_matchOver,true];
    if (_matchOver) then {_table setVariable ["Waldo_MG_TablePhase","FINISHED",true];};
    _table setVariable ["Waldo_MG_DrawPokerStatus",format ["%1 %2 %3",_reason,_summary joinString " ",if (_matchOver) then {format ["%1 wins the match. Ready a full-table rematch.",_names param [_funded param [0,-1],"Player"]]}else{"All remaining players must ready the next hand."}],true]; [_table] call Waldo_MG_fnc_drawPokerPublishServer;
};

Waldo_MG_fnc_drawPokerBeginBettingServer = {
    params [["_table",objNull],["_phase","BET1"],["_start",-1]]; if (!isServer || {isNull _table}) exitWith {};
    private _statuses=+(_table getVariable ["Waldo_MG_DrawPokerStatuses",[]]); private _chips=_table getVariable ["Waldo_MG_DrawPokerChips",[]];
    for "_i" from 0 to ((count _statuses) - 1) do {
        private _status = _statuses param [_i, ""];
        if !(_status in ["FOLDED", "LEFT", "SITOUT"]) then {
            _statuses set [_i, if ((_chips param [_i, 0]) <= 0) then {"ALLIN"} else {"ACTIVE"}];
        };
    };
    _table setVariable ["Waldo_MG_DrawPokerStatuses",_statuses,true]; _table setVariable ["Waldo_MG_DrawPokerRoundContrib",_chips apply {0},true]; _table setVariable ["Waldo_MG_DrawPokerCurrentBet",0,true]; _table setVariable ["Waldo_MG_DrawPokerMinRaise",1,true]; _table setVariable ["Waldo_MG_DrawPokerActed",_chips apply {false},true]; _table setVariable ["Waldo_MG_DrawPokerPhase",_phase,true];
    private _turn=[_start,_statuses] call Waldo_MG_fnc_drawPokerNextRole; _table setVariable ["Waldo_MG_DrawPokerTurn",_turn,true];
    if (_turn < 0) exitWith {
        if (_phase == "BET1") then {
            private _drawDone = _statuses apply {_x in ["FOLDED","LEFT","SITOUT"]};
            private _drawTurn = [_table getVariable ["Waldo_MG_DrawPokerDealer",0],_statuses,true] call Waldo_MG_fnc_drawPokerNextRole;
            _table setVariable ["Waldo_MG_DrawPokerPhase","DRAW",true]; _table setVariable ["Waldo_MG_DrawPokerDrawDone",_drawDone,true]; _table setVariable ["Waldo_MG_DrawPokerTurn",_drawTurn,true];
            _table setVariable ["Waldo_MG_DrawPokerStatus","All remaining hands are all-in. Complete the draw before showdown.",true]; [_table] call Waldo_MG_fnc_drawPokerPublishServer;
        } else {[_table,"All remaining hands are all-in."] call Waldo_MG_fnc_drawPokerResolveHandServer;};
    };
    private _names=_table getVariable ["Waldo_MG_DrawPokerPlayerNames",[]]; _table setVariable ["Waldo_MG_DrawPokerStatus",format ["%1 betting: %2 acts first.",if (_phase=="BET1") then {"Opening"}else{"Final"},_names param [_turn,"No funded player"]],true]; [_table] call Waldo_MG_fnc_drawPokerPublishServer;
};

Waldo_MG_fnc_drawPokerStartHandServer = {
    params [["_table",objNull],["_reset",false]]; if (!isServer || {isNull _table}) exitWith {false};
    private _players=_table getVariable ["Waldo_MG_DrawPokerPlayers",[]]; private _count=count _players; private _chips=+(_table getVariable ["Waldo_MG_DrawPokerChips",[]]); if (_reset) then {_chips=[];{_chips pushBack Waldo_MG_CFG_DRAWPOKER_STARTING_CHIPS;} forEach _players;};
    private _funded=[]; {if (_x>0) then {_funded pushBack _forEachIndex;};} forEach _chips;
    if ((count _funded)<=1) exitWith {private _winner=_funded param [0,-1]; _table setVariable ["Waldo_MG_DrawPokerFinished",true,true]; _table setVariable ["Waldo_MG_DrawPokerReady",_players apply {false},true]; _table setVariable ["Waldo_MG_DrawPokerPhase","FINISHED",true]; _table setVariable ["Waldo_MG_TablePhase","FINISHED",true]; _table setVariable ["Waldo_MG_DrawPokerStatus",format ["%1 is the last funded player. Ready a full-table rematch.",(_table getVariable ["Waldo_MG_DrawPokerPlayerNames",[]]) param [_winner,"Player"]],true]; [_table] call Waldo_MG_fnc_drawPokerPublishServer; true};
    private _oldDealer=_table getVariable ["Waldo_MG_DrawPokerDealer",-1]; private _dealer=_oldDealer; for "_scan" from 1 to _count do {private _candidate=(_oldDealer+_scan) mod _count;if (_dealer==_oldDealer && {_chips param [_candidate,0]>0}) then {_dealer=_candidate;};};
    private _deck=call Waldo_MG_fnc_pokerCreateShuffledDeckServer; private _hands=[]; for "_i" from 0 to (_count-1) do {_hands pushBack [];};
    for "_card" from 1 to 5 do {{if (_chips param [_forEachIndex,0]>0) then {private _hand=_hands select _forEachIndex;_hand pushBack (_deck deleteAt 0);_hands set [_forEachIndex,_hand];};} forEach _players;};
    private _statuses=[]; private _total=[]; private _antePot=0; {private _pay=(_chips param [_forEachIndex,0]) min Waldo_MG_CFG_DRAWPOKER_ANTE; _chips set [_forEachIndex,_x-_pay]; _total pushBack _pay; _antePot=_antePot+_pay; _statuses pushBack (if (_x<=0) then {"SITOUT"}else{if ((_chips param [_forEachIndex,0])<=0) then {"ALLIN"}else{"ACTIVE"}});} forEach +_chips;
    _table setVariable ["Waldo_MG_DrawPokerChips",_chips,true]; _table setVariable ["Waldo_MG_DrawPokerHandsServer",_hands,false]; _table setVariable ["Waldo_MG_DrawPokerDeckServer",_deck,false]; _table setVariable ["Waldo_MG_DrawPokerStatuses",_statuses,true]; _table setVariable ["Waldo_MG_DrawPokerTotalContrib",_total,true]; _table setVariable ["Waldo_MG_DrawPokerDealer",_dealer,true]; _table setVariable ["Waldo_MG_DrawPokerHandNumber",(_table getVariable ["Waldo_MG_DrawPokerHandNumber",0])+1,true]; _table setVariable ["Waldo_MG_DrawPokerRevealed",[],true]; _table setVariable ["Waldo_MG_DrawPokerDrawDone",_chips apply {false},true]; _table setVariable ["Waldo_MG_DrawPokerEpoch",(_table getVariable ["Waldo_MG_DrawPokerEpoch",0])+1,true]; _table setVariable ["Waldo_MG_TablePhase","PLAYING",true];
    [_table] call Waldo_MG_fnc_drawPokerSendHandsServer; [_table,"BET1",_dealer] call Waldo_MG_fnc_drawPokerBeginBettingServer; true
};

Waldo_MG_fnc_drawPokerClearServer = {
    params [["_table",objNull]]; if (!isServer || {isNull _table}) exitWith {}; {if (!isNull _x) then {_x setVariable ["Waldo_MG_DrawPokerPrivateHand",[],owner _x];};} forEach (_table getVariable ["Waldo_MG_DrawPokerPlayers",[]]);
    _table setVariable ["Waldo_MG_DrawPokerActive",false,true]; _table setVariable ["Waldo_MG_DrawPokerFinished",false,true]; _table setVariable ["Waldo_MG_DrawPokerGameId","",true]; _table setVariable ["Waldo_MG_DrawPokerPlayers",[],true]; _table setVariable ["Waldo_MG_DrawPokerHandsServer",[],false]; [_table] call Waldo_MG_fnc_drawPokerPublishServer;
};

Waldo_MG_fnc_drawPokerStartServer = {
    params [["_table",objNull]]; if (!isServer || {isNull _table}) exitWith {false}; if ([_table] call Waldo_MG_fnc_isTableGameActive) exitWith {false}; if ((_table getVariable ["Waldo_MG_TableSelectedGame",""])!="drawpoker" || {(_table getVariable ["Waldo_MG_TablePhase","LOBBY"])!="READY"}) exitWith {false};
    private _seats=[(_table getVariable ["Waldo_MG_TableSeats",[]])] call Waldo_MG_fnc_normalizeSeats; private _players=[];private _indices=[];{if (!isNull _x) then {_players pushBack _x;_indices pushBack _forEachIndex;};} forEach _seats; if ((count _players)<2 || {(count _players)>4}) exitWith {false};
    _table setVariable ["Waldo_MG_DrawPokerActive",true,true]; _table setVariable ["Waldo_MG_DrawPokerFinished",false,true]; _table setVariable ["Waldo_MG_DrawPokerGameId",format ["Waldo_MG_DP_%1_%2",floor(serverTime*10),floor random 1000000],true]; _table setVariable ["Waldo_MG_DrawPokerPlayers",_players,true]; _table setVariable ["Waldo_MG_DrawPokerPlayerNames",_players apply {name _x},true]; _table setVariable ["Waldo_MG_DrawPokerSeatIndices",_indices,true]; _table setVariable ["Waldo_MG_DrawPokerChips",_players apply {Waldo_MG_CFG_DRAWPOKER_STARTING_CHIPS},true]; _table setVariable ["Waldo_MG_DrawPokerDealer",-1,true]; _table setVariable ["Waldo_MG_DrawPokerHandNumber",0,true]; _table setVariable ["Waldo_MG_DrawPokerEpoch",0,true]; [_table,false] call Waldo_MG_fnc_drawPokerStartHandServer
};

Waldo_MG_fnc_drawPokerFinishForfeitServer = {
    params [["_table",objNull],["_unit",objNull],["_seat",-1]]; if (!isServer || {isNull _table} || {!(_table getVariable ["Waldo_MG_DrawPokerActive",false])}) exitWith {};
    private _players=_table getVariable ["Waldo_MG_DrawPokerPlayers",[]]; private _role=if (!isNull _unit) then {_players find _unit}else{(_table getVariable ["Waldo_MG_DrawPokerSeatIndices",[]]) find _seat}; if (_role<0) exitWith {};
    [_table] call Waldo_MG_fnc_drawPokerClearServer;
};

Waldo_MG_fnc_drawPokerReconcilePlayersServer = {
    params [["_table",objNull]]; if (!isServer || {isNull _table} || {!(_table getVariable ["Waldo_MG_DrawPokerActive",false])}) exitWith {}; private _seats=[(_table getVariable ["Waldo_MG_TableSeats",[]])] call Waldo_MG_fnc_normalizeSeats; private _indices=_table getVariable ["Waldo_MG_DrawPokerSeatIndices",[]];
    {private _seat=_indices param [_forEachIndex,-1];if ((_table getVariable ["Waldo_MG_DrawPokerStatuses",[]]) param [_forEachIndex,""]!="LEFT" && {isNull _x || {_seat<0} || {_seats param [_seat,objNull]!=_x} || {!alive _x}}) then {[_table,_x,_seat] call Waldo_MG_fnc_drawPokerFinishForfeitServer;};} forEach (_table getVariable ["Waldo_MG_DrawPokerPlayers",[]]);
};

Waldo_MG_fnc_drawPokerAdvanceServer = {
    params [["_table",objNull],["_role",-1]]; if (!isServer || {isNull _table}) exitWith {};
    private _statuses=_table getVariable ["Waldo_MG_DrawPokerStatuses",[]]; private _contenders=[];{if !(_x in ["FOLDED","LEFT","SITOUT"]) then {_contenders pushBack _forEachIndex;};} forEach _statuses; if ((count _contenders)<=1) exitWith {[_table,"All other hands folded."] call Waldo_MG_fnc_drawPokerResolveHandServer;};
    private _acted=_table getVariable ["Waldo_MG_DrawPokerActed",[]]; private _round=_table getVariable ["Waldo_MG_DrawPokerRoundContrib",[]]; private _bet=_table getVariable ["Waldo_MG_DrawPokerCurrentBet",0]; private _complete=true;
    {if (_x=="ACTIVE" && {!(_acted param [_forEachIndex,false]) || {(_round param [_forEachIndex,0])<_bet}}) then {_complete=false;};} forEach _statuses;
    if (!_complete) exitWith {_table setVariable ["Waldo_MG_DrawPokerTurn",[_role,_statuses] call Waldo_MG_fnc_drawPokerNextRole,true];[_table] call Waldo_MG_fnc_drawPokerPublishServer;};
    private _phase=_table getVariable ["Waldo_MG_DrawPokerPhase","BET1"];
    if (_phase=="BET1") then {
        _table setVariable ["Waldo_MG_DrawPokerPhase","DRAW",true]; _table setVariable ["Waldo_MG_DrawPokerDrawDone",_statuses apply {_x in ["FOLDED","LEFT","SITOUT"]},true]; private _next=[_table getVariable ["Waldo_MG_DrawPokerDealer",0],_statuses,true] call Waldo_MG_fnc_drawPokerNextRole; if (_next < 0) exitWith {[_table,"BET2",_table getVariable ["Waldo_MG_DrawPokerDealer",0]] call Waldo_MG_fnc_drawPokerBeginBettingServer;}; _table setVariable ["Waldo_MG_DrawPokerTurn",_next,true]; _table setVariable ["Waldo_MG_DrawPokerStatus","DRAW PHASE: select zero to three cards. Zero is STAND PAT.",true]; [_table] call Waldo_MG_fnc_drawPokerPublishServer;
    } else {[_table,"Showdown complete."] call Waldo_MG_fnc_drawPokerResolveHandServer;};
};

Waldo_MG_fnc_processDrawPokerActionRequestServer = {
    params [["_unit",objNull],["_request",[]]]; if (!isServer || {isNull _unit}) exitWith {}; if ((count _request)<6) exitWith {};
    private _token=_request param [0,""];if (!([_token] call Waldo_MG_fnc_rememberHandledTokenServer)) exitWith {};private _table=objectFromNetId(_request param [1,""]);private _gameId=_request param [2,""];private _epoch=_request param [3,-1];private _action=toUpper(_request param [4,""]);private _value=_request param [5,0];
    if (isNull _table || {_table!=(_unit getVariable ["Waldo_MG_SeatedTable",objNull])} || {!(_table getVariable ["Waldo_MG_DrawPokerActive",false])}) exitWith {[_unit,_token,"Draw Poker request rejected: stale table."] call Waldo_MG_fnc_resultServer;}; if (_gameId!=(_table getVariable ["Waldo_MG_DrawPokerGameId",""]) || {_epoch!=(_table getVariable ["Waldo_MG_DrawPokerEpoch",-2])}) exitWith {[_unit,_token,"The hand changed; review the table."] call Waldo_MG_fnc_resultServer;};
    private _role=(_table getVariable ["Waldo_MG_DrawPokerPlayers",[]]) find _unit;if (_role<0) exitWith {[_unit,_token,"Spectators cannot act."] call Waldo_MG_fnc_resultServer;};private _phase=_table getVariable ["Waldo_MG_DrawPokerPhase",""];
    if (_action=="SYNC") exitWith {[_table] call Waldo_MG_fnc_drawPokerSendHandsServer;[_unit,_token,"Private hand synchronized."] call Waldo_MG_fnc_resultServer;};
    if (_action=="READY") exitWith {if !(_phase in ["HAND_OVER","FINISHED"]) exitWith {[_unit,_token,"Finish the current hand first."] call Waldo_MG_fnc_resultServer;};private _ready=+(_table getVariable ["Waldo_MG_DrawPokerReady",[]]);_ready set [_role,true];_table setVariable ["Waldo_MG_DrawPokerReady",_ready,true];private _all=true;{if ((_table getVariable ["Waldo_MG_DrawPokerStatuses",[]]) param [_forEachIndex,""]!="LEFT" && {!(_ready param [_forEachIndex,false])}) then {_all=false;};} forEach (_table getVariable ["Waldo_MG_DrawPokerPlayers",[]]);if (_all) then {[_table,_phase=="FINISHED"] call Waldo_MG_fnc_drawPokerStartHandServer;} else {[_table] call Waldo_MG_fnc_drawPokerPublishServer;};[_unit,_token,"Ready state recorded."] call Waldo_MG_fnc_resultServer;};
    if (_role!=(_table getVariable ["Waldo_MG_DrawPokerTurn",-1])) exitWith {[_unit,_token,"Wait for your turn."] call Waldo_MG_fnc_resultServer;};
    if (_phase=="DRAW") exitWith {if (_action!="DRAW" || {(typeName _value)!="ARRAY"}) exitWith {[_unit,_token,"Select cards, then DRAW or STAND PAT."] call Waldo_MG_fnc_resultServer;};private _indices=[];{if ((typeName _x)=="SCALAR") then {_indices pushBackUnique round _x;};} forEach _value;if ((count _indices)>Waldo_MG_CFG_DRAWPOKER_MAX_DISCARDS || {{_x<0 || {_x>4}} count _indices>0}) exitWith {[_unit,_token,"Discard zero to three distinct cards."] call Waldo_MG_fnc_resultServer;};private _hands=+(_table getVariable ["Waldo_MG_DrawPokerHandsServer",[]]);private _hand=+(_hands param [_role,[]]);private _deck=+(_table getVariable ["Waldo_MG_DrawPokerDeckServer",[]]);{_hand set [_x,_deck deleteAt 0];} forEach _indices;_hands set [_role,_hand];_table setVariable ["Waldo_MG_DrawPokerHandsServer",_hands,false];_table setVariable ["Waldo_MG_DrawPokerDeckServer",_deck,false];private _done=+(_table getVariable ["Waldo_MG_DrawPokerDrawDone",[]]);_done set [_role,true];_table setVariable ["Waldo_MG_DrawPokerDrawDone",_done,true];[_table] call Waldo_MG_fnc_drawPokerSendHandsServer;private _statuses=_table getVariable ["Waldo_MG_DrawPokerStatuses",[]];private _next=-1;for "_scan" from 1 to (count _statuses) do {private _candidate=(_role+_scan) mod (count _statuses);if (_next<0 && {(_statuses param [_candidate,""]) in ["ACTIVE","ALLIN"]} && {!(_done param [_candidate,false])}) then {_next=_candidate;};};if (_next>=0) then {_table setVariable ["Waldo_MG_DrawPokerTurn",_next,true];_table setVariable ["Waldo_MG_DrawPokerStatus",format ["%1 exchanged %2. Next player draws.",name _unit,if ((count _indices)==0) then {"STAND PAT"}else{format ["%1 card(s)",count _indices]}],true];[_table] call Waldo_MG_fnc_drawPokerPublishServer;} else {[_table,"BET2",_table getVariable ["Waldo_MG_DrawPokerDealer",0]] call Waldo_MG_fnc_drawPokerBeginBettingServer;};[_unit,_token,"Draw recorded."] call Waldo_MG_fnc_resultServer;};
    if !(_phase in ["BET1","BET2"]) exitWith {[_unit,_token,"That action is not available now."] call Waldo_MG_fnc_resultServer;};private _statuses=+(_table getVariable ["Waldo_MG_DrawPokerStatuses",[]]);if ((_statuses param [_role,""])!="ACTIVE") exitWith {[_unit,_token,"Your hand cannot bet."] call Waldo_MG_fnc_resultServer;};private _chips=+(_table getVariable ["Waldo_MG_DrawPokerChips",[]]);private _round=+(_table getVariable ["Waldo_MG_DrawPokerRoundContrib",[]]);private _total=+(_table getVariable ["Waldo_MG_DrawPokerTotalContrib",[]]);private _acted=+(_table getVariable ["Waldo_MG_DrawPokerActed",[]]);private _bet=_table getVariable ["Waldo_MG_DrawPokerCurrentBet",0];private _toCall=(_bet-(_round param [_role,0])) max 0;private _pay=0;
    switch _action do {case "FOLD":{_statuses set [_role,"FOLDED"];};case "CHECK":{if (_toCall>0) exitWith {_pay=-1;};};case "CALL":{_pay=_toCall min (_chips param [_role,0]);};case "ALLIN":{_pay=_chips param [_role,0];private _allInTarget=(_round param [_role,0])+_pay;private _raiseBy=_allInTarget-_bet;if (_raiseBy>=(_table getVariable ["Waldo_MG_DrawPokerMinRaise",1])) then {_table setVariable ["Waldo_MG_DrawPokerMinRaise",_raiseBy,true];for "_i" from 0 to ((count _acted)-1) do {if (_i!=_role) then {_acted set [_i,false];};};};};case "RAISE":{private _target=round _value;if (_target<_bet+(_table getVariable ["Waldo_MG_DrawPokerMinRaise",1]) || {_target<=(_round param [_role,0])} || {_target>(_round param [_role,0])+(_chips param [_role,0])}) then {_pay=-1;} else {_pay=_target-(_round param [_role,0]);private _raiseBy=_target-_bet;_table setVariable ["Waldo_MG_DrawPokerMinRaise",_raiseBy,true];_bet=_target;for "_i" from 0 to ((count _acted)-1) do {if (_i!=_role) then {_acted set [_i,false];};};};};default {_pay=-1;};};
    if (_pay<0) exitWith {[_unit,_token,"Illegal betting action or raise amount."] call Waldo_MG_fnc_resultServer;};if (_pay>0) then {_chips set [_role,(_chips param [_role,0])-_pay];_round set [_role,(_round param [_role,0])+_pay];_total set [_role,(_total param [_role,0])+_pay];if ((_round param [_role,0])>_bet) then {_bet=_round param [_role,0];};if ((_chips param [_role,0])<=0) then {_statuses set [_role,"ALLIN"];};};_acted set [_role,true];_table setVariable ["Waldo_MG_DrawPokerStatuses",_statuses,true];_table setVariable ["Waldo_MG_DrawPokerChips",_chips,true];_table setVariable ["Waldo_MG_DrawPokerRoundContrib",_round,true];_table setVariable ["Waldo_MG_DrawPokerTotalContrib",_total,true];_table setVariable ["Waldo_MG_DrawPokerActed",_acted,true];_table setVariable ["Waldo_MG_DrawPokerCurrentBet",_bet,true];_table setVariable ["Waldo_MG_DrawPokerEpoch",_epoch+1,true];_table setVariable ["Waldo_MG_DrawPokerStatus",format ["%1: %2.",name _unit,_action],true];[_table,_role] call Waldo_MG_fnc_drawPokerAdvanceServer;[_unit,_token,"Action accepted."] call Waldo_MG_fnc_resultServer;
};

Waldo_MG_fnc_submitDrawPokerActionLocal = {params [["_table",objNull],["_action","CHECK"],["_value",0]];if (!hasInterface||{isNull _table}) exitWith {};private _token=["DRAWPOKER"] call Waldo_MG_fnc_makeToken;private _request=[_token,netId _table,_table getVariable ["Waldo_MG_DrawPokerGameId",""],_table getVariable ["Waldo_MG_DrawPokerEpoch",-1],_action,_value];["DRAWPOKER",_table,_token,_request param [3,-1],_request] call Waldo_MG_fnc_submitRequestLocal;};

Waldo_MG_fnc_refreshDrawPokerLocal = {
    disableSerialization;params [["_display",displayNull]];if (isNull _display) exitWith {};private _table=_display getVariable ["Waldo_MG_DrawPokerTable",objNull];if (isNull _table) exitWith {_display closeDisplay 1;};private _revision=_table getVariable ["Waldo_MG_DrawPokerRevision",0];_display setVariable ["Waldo_MG_DrawPokerLastRevision",_revision];
    private _role=(_table getVariable ["Waldo_MG_DrawPokerPlayers",[]]) find player;private _phase=_table getVariable ["Waldo_MG_DrawPokerPhase",""];private _turn=_table getVariable ["Waldo_MG_DrawPokerTurn",-1];private _private=player getVariable ["Waldo_MG_DrawPokerPrivateHand",[]];private _hand=if ((_private param [0,""])==(_table getVariable ["Waldo_MG_DrawPokerGameId",""])) then {_private param [2,[]]}else{[]};private _selected=_display getVariable ["Waldo_MG_DrawPokerSelected",[]];
    if (_role>=0 && {(count _hand)<5} && {(diag_tickTime-(_display getVariable ["Waldo_MG_DrawPokerLastSync",-10]))>2.5}) then {_display setVariable ["Waldo_MG_DrawPokerLastSync",diag_tickTime];[_table,"SYNC",0] call Waldo_MG_fnc_submitDrawPokerActionLocal;};
    private _renderKey=[_revision,_private,_selected];if (_renderKey isEqualTo (_display getVariable ["Waldo_MG_DrawPokerRenderKey",[]])) exitWith {};_display setVariable ["Waldo_MG_DrawPokerRenderKey",_renderKey];
    {private _card=_hand param [_forEachIndex,-1];private _selectionLabel=if (_forEachIndex in _selected) then {"DISCARD"}else{"KEEP"};_x ctrlSetText (if (_card>=0) then {format ["%1  %2  %3",_selectionLabel,[[_card] call Waldo_MG_fnc_pokerCardRank] call Waldo_MG_fnc_pokerRankLabel,[[_card] call Waldo_MG_fnc_pokerCardSuit] call Waldo_MG_fnc_pokerSuitLetter]}else{"CARD BACK"});_x ctrlSetBackgroundColor (if (_forEachIndex in _selected) then {[0.42,0.18,0.05,1]}else{[0.94,0.92,0.82,1]});_x ctrlSetTextColor [0.05,0.06,0.07,1];_x ctrlEnable (_role==_turn && {_phase=="DRAW"} && {_card>=0});} forEach (_display getVariable ["Waldo_MG_DrawPokerCards",[]]);
    private _names=_table getVariable ["Waldo_MG_DrawPokerPlayerNames",[]];private _chips=_table getVariable ["Waldo_MG_DrawPokerChips",[]];private _statuses=_table getVariable ["Waldo_MG_DrawPokerStatuses",[]];private _round=_table getVariable ["Waldo_MG_DrawPokerRoundContrib",[]];private _dealer=_table getVariable ["Waldo_MG_DrawPokerDealer",-1];private _lines=[];{_lines pushBack format ["%1%2 | %3 CHIPS | BET %4 | %5%6",if (_forEachIndex==_dealer) then {"[D] "}else{""},_names param [_forEachIndex,"Player"],_chips param [_forEachIndex,0],_round param [_forEachIndex,0],_x,if (_forEachIndex==_turn) then {" | ACTING"}else{""}];} forEach _statuses;private _roster=_display getVariable ["Waldo_MG_DrawPokerRoster",controlNull];if (!isNull _roster) then {_roster ctrlSetStructuredText parseText (_lines joinString "<br/><br/>");};
    private _pot=0;{_pot=_pot+_x;} forEach (_table getVariable ["Waldo_MG_DrawPokerTotalContrib",[]]);private _info=_display getVariable ["Waldo_MG_DrawPokerInfo",controlNull];if (!isNull _info) then {_info ctrlSetText format ["HAND %1  |  %2  |  POT %3  |  CALL %4  |  MIN RAISE %5",_table getVariable ["Waldo_MG_DrawPokerHandNumber",0],_phase,_pot,((_table getVariable ["Waldo_MG_DrawPokerCurrentBet",0])-(_round param [_role,0])) max 0,_table getVariable ["Waldo_MG_DrawPokerMinRaise",1]];};private _status=_display getVariable ["Waldo_MG_DrawPokerStatusCtrl",controlNull];if (!isNull _status) then {_status ctrlSetText (_table getVariable ["Waldo_MG_DrawPokerStatus",""]);};
    private _canBet=_role==_turn && {_phase in ["BET1","BET2"]};{_x ctrlEnable _canBet;} forEach (_display getVariable ["Waldo_MG_DrawPokerBetControls",[]]);private _draw=_display getVariable ["Waldo_MG_DrawPokerDrawButton",controlNull];if (!isNull _draw) then {_draw ctrlShow (_role==_turn && {_phase=="DRAW"});_draw ctrlSetText (if ((count _selected)==0) then {"STAND PAT"}else{format ["DRAW %1 CARD(S)",count _selected]});};private _ready=_display getVariable ["Waldo_MG_DrawPokerReadyButton",controlNull];if (!isNull _ready) then {_ready ctrlShow (_role>=0 && {_phase in ["HAND_OVER","FINISHED"]});};
};

Waldo_MG_fnc_openDrawPokerLocal = {
    disableSerialization;params [["_table",objNull],["_spectating",false]];if (!hasInterface||{isNull _table}||{!([_table,_spectating] call Waldo_MG_fnc_isValidGameViewerLocal)}||{([_table] call Waldo_MG_fnc_getTableActiveGameId)!="drawpoker"}) exitWith {["No active Five-Card Draw table is available."] call Waldo_MG_fnc_notifyLocal;};private _parent=findDisplay 46;if (isNull _parent) exitWith {};call Waldo_MG_fnc_closeTableGameDisplaysLocal;private _display=_parent createDisplay "RscDisplayEmpty";uiNamespace setVariable ["Waldo_MG_DrawPokerDisplay",_display];_display setVariable ["Waldo_MG_TableGameDisplay",true];_display setVariable ["Waldo_MG_DrawPokerTable",_table];_display setVariable ["Waldo_MG_SpectatorMode",_spectating];_display setVariable ["Waldo_MG_DrawPokerLastRevision",-1];_display setVariable ["Waldo_MG_DrawPokerSelected",[]];[_display] call Waldo_MG_fnc_installEscapeGuardLocal;
    private _bg=_display ctrlCreate ["RscText",-1];_bg ctrlSetPosition [safezoneX,safezoneY,safezoneW,safezoneH];_bg ctrlSetBackgroundColor [0.006,0.025,0.018,0.99];_bg ctrlCommit 0;private _header=_display ctrlCreate ["RscText",-1];_header ctrlSetPosition [safezoneX,safezoneY,safezoneW,0.08*safezoneH];_header ctrlSetBackgroundColor [0.035,0.22,0.14,1];_header ctrlSetText "  WALDOS MINI GAMES  /  FIVE-CARD DRAW";_header ctrlSetFontHeight (0.032*safezoneH);_header ctrlCommit 0;
    private _info=_display ctrlCreate ["RscText",-1];_info ctrlSetPosition [safezoneX+0.05*safezoneW,safezoneY+0.11*safezoneH,0.90*safezoneW,0.065*safezoneH];_info ctrlSetBackgroundColor [0.025,0.10,0.07,1];_info ctrlSetFontHeight (0.021*safezoneH);_info ctrlCommit 0;private _cards=[];for "_i" from 0 to 4 do {private _card=_display ctrlCreate ["RscButton",-1];_card ctrlSetPosition [safezoneX+(0.07+_i*0.115)*safezoneW,safezoneY+0.22*safezoneH,0.10*safezoneW,0.22*safezoneH];_card setVariable ["Waldo_MG_DrawPokerCardIndex",_i];_card ctrlSetFontHeight (0.035*safezoneH);_card ctrlAddEventHandler ["ButtonClick",{params ["_c"];private _d=ctrlParent _c;private _i=_c getVariable ["Waldo_MG_DrawPokerCardIndex",-1];private _s=+(_d getVariable ["Waldo_MG_DrawPokerSelected",[]]);if (_i in _s) then {_s deleteAt (_s find _i);}else{if ((count _s)<Waldo_MG_CFG_DRAWPOKER_MAX_DISCARDS) then {_s pushBack _i;};};_d setVariable ["Waldo_MG_DrawPokerSelected",_s];_d setVariable ["Waldo_MG_DrawPokerLastRevision",-1];}];_card ctrlCommit 0;_cards pushBack _card;};
    private _roster=_display ctrlCreate ["RscStructuredText",-1];_roster ctrlSetPosition [safezoneX+0.67*safezoneW,safezoneY+0.22*safezoneH,0.28*safezoneW,0.35*safezoneH];_roster ctrlSetBackgroundColor [0.015,0.065,0.045,1];_roster ctrlSetFontHeight (0.017*safezoneH);_roster ctrlCommit 0;private _actions=[];private _labels=[["FOLD","FOLD"],["CHECK","CHECK"],["CALL","CALL"],["ALL IN","ALLIN"]];{private _b=_display ctrlCreate ["RscButtonMenu",-1];_b ctrlSetPosition [safezoneX+(0.07+_forEachIndex*0.14)*safezoneW,safezoneY+0.50*safezoneH,0.125*safezoneW,0.052*safezoneH];_b ctrlSetText (_x select 0);_b setVariable ["Waldo_MG_DrawPokerAction",_x select 1];_b ctrlAddEventHandler ["ButtonClick",{params ["_c"];private _d=ctrlParent _c;[_d getVariable ["Waldo_MG_DrawPokerTable",objNull],_c getVariable ["Waldo_MG_DrawPokerAction","CHECK"],0] call Waldo_MG_fnc_submitDrawPokerActionLocal;}];_b ctrlCommit 0;_actions pushBack _b;} forEach _labels;
    private _raiseEdit=_display ctrlCreate ["RscEdit",-1];_raiseEdit ctrlSetPosition [safezoneX+0.07*safezoneW,safezoneY+0.575*safezoneH,0.18*safezoneW,0.052*safezoneH];_raiseEdit ctrlSetText "2";_raiseEdit ctrlCommit 0;private _raise=_display ctrlCreate ["RscButtonMenu",-1];_raise ctrlSetPosition [safezoneX+0.27*safezoneW,safezoneY+0.575*safezoneH,0.20*safezoneW,0.052*safezoneH];_raise ctrlSetText "RAISE TO";_raise ctrlAddEventHandler ["ButtonClick",{params ["_c"];private _d=ctrlParent _c;private _e=_d getVariable ["Waldo_MG_DrawPokerRaiseEdit",controlNull];[_d getVariable ["Waldo_MG_DrawPokerTable",objNull],"RAISE",parseNumber(ctrlText _e)] call Waldo_MG_fnc_submitDrawPokerActionLocal;}];_raise ctrlCommit 0;_actions append [_raiseEdit,_raise];
    private _draw=_display ctrlCreate ["RscButtonMenu",-1];_draw ctrlSetPosition [safezoneX+0.07*safezoneW,safezoneY+0.66*safezoneH,0.40*safezoneW,0.06*safezoneH];_draw ctrlAddEventHandler ["ButtonClick",{params ["_c"];private _d=ctrlParent _c;[_d getVariable ["Waldo_MG_DrawPokerTable",objNull],"DRAW",+(_d getVariable ["Waldo_MG_DrawPokerSelected",[]])] call Waldo_MG_fnc_submitDrawPokerActionLocal;_d setVariable ["Waldo_MG_DrawPokerSelected",[]];}];_draw ctrlCommit 0;private _rules=_display ctrlCreate ["RscStructuredText",-1];_rules ctrlSetPosition [safezoneX+0.67*safezoneW,safezoneY+0.60*safezoneH,0.28*safezoneW,0.18*safezoneH];_rules ctrlSetStructuredText parseText "<t color='#8FD9AE'>TABLE PROCEDURE</t><br/>Ante 1. Bet, exchange 0-3 cards, then bet again.<br/>Zero selected means STAND PAT.<br/>Cards show rank and suit letter; colour is supplementary.";_rules ctrlCommit 0;
    private _ready=_display ctrlCreate ["RscButtonMenu",-1];_ready ctrlSetPosition [safezoneX+0.67*safezoneW,safezoneY+0.80*safezoneH,0.17*safezoneW,0.05*safezoneH];_ready ctrlSetText "READY NEXT";_ready ctrlAddEventHandler ["ButtonClick",{params ["_c"];private _d=ctrlParent _c;[_d getVariable ["Waldo_MG_DrawPokerTable",objNull],"READY",0] call Waldo_MG_fnc_submitDrawPokerActionLocal;}];_ready ctrlCommit 0;private _leave=_display ctrlCreate ["RscButtonMenu",-1];_leave ctrlSetPosition [safezoneX+0.85*safezoneW,safezoneY+0.80*safezoneH,0.10*safezoneW,0.05*safezoneH];_leave ctrlSetText "EXIT";_leave ctrlAddEventHandler ["ButtonClick",{params ["_c"];[_c] call Waldo_MG_fnc_handleViewerExitButtonLocal;}];_leave ctrlCommit 0;private _status=_display ctrlCreate ["RscText",-1];_status ctrlSetPosition [safezoneX+0.05*safezoneW,safezoneY+0.88*safezoneH,0.90*safezoneW,0.06*safezoneH];_status ctrlSetBackgroundColor [0.025,0.10,0.07,1];_status ctrlSetFontHeight (0.017*safezoneH);_status ctrlCommit 0;
    _display setVariable ["Waldo_MG_DrawPokerCards",_cards];_display setVariable ["Waldo_MG_DrawPokerInfo",_info];_display setVariable ["Waldo_MG_DrawPokerRoster",_roster];_display setVariable ["Waldo_MG_DrawPokerBetControls",_actions];_display setVariable ["Waldo_MG_DrawPokerRaiseEdit",_raiseEdit];_display setVariable ["Waldo_MG_DrawPokerDrawButton",_draw];_display setVariable ["Waldo_MG_DrawPokerReadyButton",_ready];_display setVariable ["Waldo_MG_DrawPokerStatusCtrl",_status];[_display] call Waldo_MG_fnc_refreshDrawPokerLocal;[_display] spawn {disableSerialization;params ["_d"];while {!isNull _d} do {[_d] call Waldo_MG_fnc_refreshDrawPokerLocal;uiSleep Waldo_MG_CFG_DRAWPOKER_UI_TICK;};};
};
